// Code generated by bencgen go. DO NOT EDIT.
// source: testing/schemas/custom.benc

package custom

import (
	"github.com/alvarolm/benc/impl/gen"
	"github.com/alvarolm/benc/std"

	"github.com/alvarolm/benc/testing/custom/codecs"
)

// Custom - Name
type Name string

func nameSize(v Name) int                     { return bstd.SizeString(string(v)) }
func nameMarshal(n int, b []byte, v Name) int { return bstd.MarshalString(n, b, string(v)) }
func nameUnmarshal(n int, b []byte) (int, Name, error) {
	n, v, err := bstd.UnmarshalString(n, b)
	return n, Name(v), err
}

// Custom - UserID
type UserID uint64

func userIDSize(_ UserID) int                     { return bstd.SizeUint64() }
func userIDMarshal(n int, b []byte, v UserID) int { return bstd.MarshalUint64(n, b, uint64(v)) }
func userIDUnmarshal(n int, b []byte) (int, UserID, error) {
	n, v, err := bstd.UnmarshalUint64(n, b)
	return n, UserID(v), err
}

// Struct - Record
type Record struct {
	Name    Name
	Id      UserID
	Created codecs.Stamp
	Tags    []Name
	Idx     map[Name]UserID
	Stamps  []codecs.Stamp
}

// Reserved Ids - Record
var recordRIds = []uint16{}

// Size - Record
func (record *Record) Size() int {
	return record.NestedSize(0)
}

// Nested Size - Record
func (record *Record) NestedSize(id uint16) (s int) {
	s += nameSize(record.Name) + 2
	s += userIDSize(record.Id) + 2
	s += codecs.SizeStamp(record.Created) + 2
	s += bstd.SizeSlice(record.Tags, nameSize) + 2
	s += bstd.SizeMap(record.Idx, nameSize, userIDSize) + 2
	s += bstd.SizeSlice(record.Stamps, codecs.SizeStamp) + 2

	if id > 255 {
		s += 5
		return
	}
	s += 4
	return
}

// SizePlain - Record
func (record *Record) SizePlain() (s int) {
	s += nameSize(record.Name)
	s += userIDSize(record.Id)
	s += codecs.SizeStamp(record.Created)
	s += bstd.SizeSlice(record.Tags, nameSize)
	s += bstd.SizeMap(record.Idx, nameSize, userIDSize)
	s += bstd.SizeSlice(record.Stamps, codecs.SizeStamp)
	return
}

// Marshal - Record
func (record *Record) Marshal(b []byte) {
	record.NestedMarshal(0, b, 0)
}

// Nested Marshal - Record
func (record *Record) NestedMarshal(tn int, b []byte, id uint16) (n int) {
	n = bgenimpl.MarshalTag(tn, b, bgenimpl.Container, id)
	n = bgenimpl.MarshalTag(n, b, bgenimpl.Bytes, 1)
	n = nameMarshal(n, b, record.Name)
	n = bgenimpl.MarshalTag(n, b, bgenimpl.Fixed64, 2)
	n = userIDMarshal(n, b, record.Id)
	n = bgenimpl.MarshalTag(n, b, bgenimpl.Bytes, 3)
	n = codecs.MarshalStamp(n, b, record.Created)
	n = bgenimpl.MarshalTag(n, b, bgenimpl.ArrayMap, 4)
	n = bstd.MarshalSlice(n, b, record.Tags, nameMarshal)
	n = bgenimpl.MarshalTag(n, b, bgenimpl.ArrayMap, 5)
	n = bstd.MarshalMap(n, b, record.Idx, nameMarshal, userIDMarshal)
	n = bgenimpl.MarshalTag(n, b, bgenimpl.ArrayMap, 6)
	n = bstd.MarshalSlice(n, b, record.Stamps, codecs.MarshalStamp)

	n += 2
	b[n-2] = 1
	b[n-1] = 1
	return
}

// MarshalPlain - Record
func (record *Record) MarshalPlain(tn int, b []byte) (n int) {
	n = tn
	n = nameMarshal(n, b, record.Name)
	n = userIDMarshal(n, b, record.Id)
	n = codecs.MarshalStamp(n, b, record.Created)
	n = bstd.MarshalSlice(n, b, record.Tags, nameMarshal)
	n = bstd.MarshalMap(n, b, record.Idx, nameMarshal, userIDMarshal)
	n = bstd.MarshalSlice(n, b, record.Stamps, codecs.MarshalStamp)
	return n
}

// Unmarshal - Record
func (record *Record) Unmarshal(b []byte) (err error) {
	_, err = record.NestedUnmarshal(0, b, []uint16{}, 0)
	return
}

// Nested Unmarshal - Record
func (record *Record) NestedUnmarshal(tn int, b []byte, r []uint16, id uint16) (n int, err error) {
	var ok bool
	if n, ok, err = bgenimpl.HandleCompatibility(tn, b, r, id); !ok {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, recordRIds, 1); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, record.Name, err = nameUnmarshal(n, b); err != nil {
			return
		}
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, recordRIds, 2); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, record.Id, err = userIDUnmarshal(n, b); err != nil {
			return
		}
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, recordRIds, 3); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, record.Created, err = codecs.UnmarshalStamp(n, b); err != nil {
			return
		}
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, recordRIds, 4); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, record.Tags, err = bstd.UnmarshalSlice[Name](n, b, nameUnmarshal); err != nil {
			return
		}
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, recordRIds, 5); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, record.Idx, err = bstd.UnmarshalMap[Name, UserID](n, b, nameUnmarshal, userIDUnmarshal); err != nil {
			return
		}
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, recordRIds, 6); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, record.Stamps, err = bstd.UnmarshalSlice[codecs.Stamp](n, b, codecs.UnmarshalStamp); err != nil {
			return
		}
	}
	n += 2
	return
}

// UnmarshalPlain - Record
func (record *Record) UnmarshalPlain(tn int, b []byte) (n int, err error) {
	n = tn
	if n, record.Name, err = nameUnmarshal(n, b); err != nil {
		return
	}
	if n, record.Id, err = userIDUnmarshal(n, b); err != nil {
		return
	}
	if n, record.Created, err = codecs.UnmarshalStamp(n, b); err != nil {
		return
	}
	if n, record.Tags, err = bstd.UnmarshalSlice[Name](n, b, nameUnmarshal); err != nil {
		return
	}
	if n, record.Idx, err = bstd.UnmarshalMap[Name, UserID](n, b, nameUnmarshal, userIDUnmarshal); err != nil {
		return
	}
	if n, record.Stamps, err = bstd.UnmarshalSlice[codecs.Stamp](n, b, codecs.UnmarshalStamp); err != nil {
		return
	}
	return
}
