// Code generated by bencgen go. DO NOT EDIT.
// source: testing/schemas/fixed_arrays.benc

package fixedarrays

import (
	"github.com/alvarolm/benc/impl/gen"
	"github.com/alvarolm/benc/std"
)

// Custom - Name
type Name string

func nameSize(v Name) int                     { return bstd.SizeString(string(v)) }
func nameMarshal(n int, b []byte, v Name) int { return bstd.MarshalString(n, b, string(v)) }
func nameUnmarshal(n int, b []byte) (int, Name, error) {
	n, v, err := bstd.UnmarshalString(n, b)
	return n, Name(v), err
}

// Struct - Point
type Point struct {
	X int32
	Y int32
}

// Reserved Ids - Point
var pointRIds = []uint16{}

// Size - Point
func (point *Point) Size() int {
	return point.NestedSize(0)
}

// Nested Size - Point
func (point *Point) NestedSize(id uint16) (s int) {
	s += bstd.SizeInt32() + 2
	s += bstd.SizeInt32() + 2

	if id > 255 {
		s += 5
		return
	}
	s += 4
	return
}

// SizePlain - Point
func (point *Point) SizePlain() (s int) {
	s += bstd.SizeInt32()
	s += bstd.SizeInt32()
	return
}

// Marshal - Point
func (point *Point) Marshal(b []byte) {
	point.NestedMarshal(0, b, 0)
}

// Nested Marshal - Point
func (point *Point) NestedMarshal(tn int, b []byte, id uint16) (n int) {
	n = bgenimpl.MarshalTag(tn, b, bgenimpl.Container, id)
	n = bgenimpl.MarshalTag(n, b, bgenimpl.Fixed32, 1)
	n = bstd.MarshalInt32(n, b, point.X)
	n = bgenimpl.MarshalTag(n, b, bgenimpl.Fixed32, 2)
	n = bstd.MarshalInt32(n, b, point.Y)

	n += 2
	b[n-2] = 1
	b[n-1] = 1
	return
}

// MarshalPlain - Point
func (point *Point) MarshalPlain(tn int, b []byte) (n int) {
	n = tn
	n = bstd.MarshalInt32(n, b, point.X)
	n = bstd.MarshalInt32(n, b, point.Y)
	return n
}

// Unmarshal - Point
func (point *Point) Unmarshal(b []byte) (err error) {
	_, err = point.NestedUnmarshal(0, b, []uint16{}, 0)
	return
}

// Nested Unmarshal - Point
func (point *Point) NestedUnmarshal(tn int, b []byte, r []uint16, id uint16) (n int, err error) {
	var ok bool
	if n, ok, err = bgenimpl.HandleCompatibility(tn, b, r, id); !ok {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, pointRIds, 1); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, point.X, err = bstd.UnmarshalInt32(n, b); err != nil {
			return
		}
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, pointRIds, 2); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, point.Y, err = bstd.UnmarshalInt32(n, b); err != nil {
			return
		}
	}
	n += 2
	return
}

// UnmarshalPlain - Point
func (point *Point) UnmarshalPlain(tn int, b []byte) (n int, err error) {
	n = tn
	if n, point.X, err = bstd.UnmarshalInt32(n, b); err != nil {
		return
	}
	if n, point.Y, err = bstd.UnmarshalInt32(n, b); err != nil {
		return
	}
	return
}

// Struct - Shapes
type Shapes struct {
	Hash    [16]byte
	Quad    [4]int32
	Labels  [3]string
	Points  [2]Point
	Aliases [3]Name
	Matrix  [][3]int32
}

// Reserved Ids - Shapes
var shapesRIds = []uint16{}

// Size - Shapes
func (shapes *Shapes) Size() int {
	return shapes.NestedSize(0)
}

// Nested Size - Shapes
func (shapes *Shapes) NestedSize(id uint16) (s int) {
	s += bstd.SizeFixedSlice(shapes.Hash[:], bstd.SizeByte()) + 2
	s += bstd.SizeFixedSlice(shapes.Quad[:], bstd.SizeInt32()) + 2
	s += bstd.SizeSlice(shapes.Labels[:], bstd.SizeString) + 2
	s += bstd.SizeSlice(shapes.Points[:], func(s Point) int { return s.SizePlain() }) + 2
	s += bstd.SizeSlice(shapes.Aliases[:], nameSize) + 2
	s += bstd.SizeSlice(shapes.Matrix, func(s [3]int32) int { return bstd.SizeFixedSlice(s[:], bstd.SizeInt32()) }) + 2

	if id > 255 {
		s += 5
		return
	}
	s += 4
	return
}

// SizePlain - Shapes
func (shapes *Shapes) SizePlain() (s int) {
	s += bstd.SizeFixedSlice(shapes.Hash[:], bstd.SizeByte())
	s += bstd.SizeFixedSlice(shapes.Quad[:], bstd.SizeInt32())
	s += bstd.SizeSlice(shapes.Labels[:], bstd.SizeString)
	s += bstd.SizeSlice(shapes.Points[:], func(s Point) int { return s.SizePlain() })
	s += bstd.SizeSlice(shapes.Aliases[:], nameSize)
	s += bstd.SizeSlice(shapes.Matrix, func(s [3]int32) int { return bstd.SizeFixedSlice(s[:], bstd.SizeInt32()) })
	return
}

// Marshal - Shapes
func (shapes *Shapes) Marshal(b []byte) {
	shapes.NestedMarshal(0, b, 0)
}

// Nested Marshal - Shapes
func (shapes *Shapes) NestedMarshal(tn int, b []byte, id uint16) (n int) {
	n = bgenimpl.MarshalTag(tn, b, bgenimpl.Container, id)
	n = bgenimpl.MarshalTag(n, b, bgenimpl.ArrayMap, 1)
	n = bstd.MarshalFixedByteArray(n, b, shapes.Hash[:])
	n = bgenimpl.MarshalTag(n, b, bgenimpl.ArrayMap, 2)
	n = bstd.MarshalSlice(n, b, shapes.Quad[:], bstd.MarshalInt32)
	n = bgenimpl.MarshalTag(n, b, bgenimpl.ArrayMap, 3)
	n = bstd.MarshalSlice(n, b, shapes.Labels[:], bstd.MarshalString)
	n = bgenimpl.MarshalTag(n, b, bgenimpl.ArrayMap, 4)
	n = bstd.MarshalSlice(n, b, shapes.Points[:], func(n int, b []byte, s Point) int { return s.MarshalPlain(n, b) })
	n = bgenimpl.MarshalTag(n, b, bgenimpl.ArrayMap, 5)
	n = bstd.MarshalSlice(n, b, shapes.Aliases[:], nameMarshal)
	n = bgenimpl.MarshalTag(n, b, bgenimpl.ArrayMap, 6)
	n = bstd.MarshalSlice(n, b, shapes.Matrix, func(n int, b []byte, s [3]int32) int { return bstd.MarshalSlice(n, b, s[:], bstd.MarshalInt32) })

	n += 2
	b[n-2] = 1
	b[n-1] = 1
	return
}

// MarshalPlain - Shapes
func (shapes *Shapes) MarshalPlain(tn int, b []byte) (n int) {
	n = tn
	n = bstd.MarshalFixedByteArray(n, b, shapes.Hash[:])
	n = bstd.MarshalSlice(n, b, shapes.Quad[:], bstd.MarshalInt32)
	n = bstd.MarshalSlice(n, b, shapes.Labels[:], bstd.MarshalString)
	n = bstd.MarshalSlice(n, b, shapes.Points[:], func(n int, b []byte, s Point) int { return s.MarshalPlain(n, b) })
	n = bstd.MarshalSlice(n, b, shapes.Aliases[:], nameMarshal)
	n = bstd.MarshalSlice(n, b, shapes.Matrix, func(n int, b []byte, s [3]int32) int { return bstd.MarshalSlice(n, b, s[:], bstd.MarshalInt32) })
	return n
}

// Unmarshal - Shapes
func (shapes *Shapes) Unmarshal(b []byte) (err error) {
	_, err = shapes.NestedUnmarshal(0, b, []uint16{}, 0)
	return
}

// Nested Unmarshal - Shapes
func (shapes *Shapes) NestedUnmarshal(tn int, b []byte, r []uint16, id uint16) (n int, err error) {
	var ok bool
	if n, ok, err = bgenimpl.HandleCompatibility(tn, b, r, id); !ok {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, shapesRIds, 1); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, err = bstd.UnmarshalFixedByteArray(n, b, shapes.Hash[:]); err != nil {
			return
		}
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, shapesRIds, 2); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, err = bstd.UnmarshalFixedArray(n, b, shapes.Quad[:], bstd.UnmarshalInt32); err != nil {
			return
		}
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, shapesRIds, 3); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, err = bstd.UnmarshalFixedArray(n, b, shapes.Labels[:], bstd.UnmarshalString); err != nil {
			return
		}
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, shapesRIds, 4); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, err = bstd.UnmarshalFixedArray(n, b, shapes.Points[:], func(n int, b []byte, s *Point) (int, error) { return s.UnmarshalPlain(n, b) }); err != nil {
			return
		}
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, shapesRIds, 5); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, err = bstd.UnmarshalFixedArray(n, b, shapes.Aliases[:], nameUnmarshal); err != nil {
			return
		}
	}
	if n, ok, err = bgenimpl.HandleCompatibility(n, b, shapesRIds, 6); err != nil {
		if err == bgenimpl.ErrEof {
			return n, nil
		}
		return
	}
	if ok {
		if n, shapes.Matrix, err = bstd.UnmarshalSlice[[3]int32](n, b, func(n int, b []byte) (int, [3]int32, error) {
			var a [3]int32
			n, err := bstd.UnmarshalFixedArray(n, b, a[:], bstd.UnmarshalInt32)
			return n, a, err
		}); err != nil {
			return
		}
	}
	n += 2
	return
}

// UnmarshalPlain - Shapes
func (shapes *Shapes) UnmarshalPlain(tn int, b []byte) (n int, err error) {
	n = tn
	if n, err = bstd.UnmarshalFixedByteArray(n, b, shapes.Hash[:]); err != nil {
		return
	}
	if n, err = bstd.UnmarshalFixedArray(n, b, shapes.Quad[:], bstd.UnmarshalInt32); err != nil {
		return
	}
	if n, err = bstd.UnmarshalFixedArray(n, b, shapes.Labels[:], bstd.UnmarshalString); err != nil {
		return
	}
	if n, err = bstd.UnmarshalFixedArray(n, b, shapes.Points[:], func(n int, b []byte, s *Point) (int, error) { return s.UnmarshalPlain(n, b) }); err != nil {
		return
	}
	if n, err = bstd.UnmarshalFixedArray(n, b, shapes.Aliases[:], nameUnmarshal); err != nil {
		return
	}
	if n, shapes.Matrix, err = bstd.UnmarshalSlice[[3]int32](n, b, func(n int, b []byte) (int, [3]int32, error) {
		var a [3]int32
		n, err := bstd.UnmarshalFixedArray(n, b, a[:], bstd.UnmarshalInt32)
		return n, a, err
	}); err != nil {
		return
	}
	return
}
